/**
* LibraryCatalog
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param biography 
 */

data class AuthorDto (
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "biography")
    val biography: kotlin.String? = null
) 



