/**
* LibraryCatalog
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param title 
 * @param description 
 * @param authorsIds 
 * @param reviewsIds 
 * @param publisherId 
 */

data class PublicationDto (
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "authorsIds")
    val authorsIds: kotlin.Array<kotlin.Int>? = null,
    @Json(name = "reviewsIds")
    val reviewsIds: kotlin.Array<kotlin.Int>? = null,
    @Json(name = "publisherId")
    val publisherId: kotlin.Int? = null
) 



