/**
* LibraryCatalog
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param reviewerName 
 * @param isPositive 
 */

data class ReviewBriefDto (
    @Json(name = "id")
    val id: kotlin.Int? = null,
    @Json(name = "reviewerName")
    val reviewerName: kotlin.String? = null,
    @Json(name = "isPositive")
    val isPositive: kotlin.Boolean? = null
) 



